import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { generateMealPlan } from '../utils/geminiAPI';
import MealPlanDisplay from '../src/components/MealPlanDisplay';

const Diet = () => {
  const [preferences, setPreferences] = useState('');
  const [mealPlan, setMealPlan] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleGenerateMealPlan = async () => {
    if (!preferences.trim()) {
      Alert.alert('Error', 'Please enter your dietary preferences');
      return;
    }

    setLoading(true);
    try {
      const data = await generateMealPlan(preferences);
      if (data) {
        setMealPlan(data);
      }
    } catch (error) {
      console.error('Error:', error);
      Alert.alert(
        'Error',
        'Failed to generate meal plan. Please try again.'
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>AI-Powered Meal Plan</Text>
        {/* <Text style={styles.subtitle}>Generated by Gemini</Text> */}
      </View>

      <View style={styles.exampleContainer}>
        <Text style={styles.exampleTitle}>Example preferences:</Text>
        <Text style={styles.exampleText}>• "vegetarian, high protein"</Text>
        <Text style={styles.exampleText}>• "low carb, dairy free"</Text>
        <Text style={styles.exampleText}>• "gluten free, 2000 calories"</Text>
      </View>

      <View style={styles.inputContainer}>
        <Ionicons name="nutrition-outline" size={24} color="#666" style={styles.inputIcon} />
        <TextInput
          style={styles.input}
          placeholder="Enter preferences (e.g., vegetarian, low-carb, allergies)"
          value={preferences}
          onChangeText={setPreferences}
          multiline
          numberOfLines={3}
          placeholderTextColor="#666"
        />
      </View>

      <TouchableOpacity
        style={[styles.generateButton, loading && styles.generateButtonDisabled]}
        onPress={handleGenerateMealPlan}
        disabled={loading}
      >
        {loading ? (
          <View style={styles.loadingContainer}>
            <ActivityIndicator color="#fff" style={styles.loadingIcon} />
            <Text style={styles.buttonText}>Generating...</Text>
          </View>
        ) : (
          <View style={styles.buttonContainer}>
            <Ionicons name="create-outline" size={24} color="#fff" />
            {/* <Text style={styles.buttonText}>Generate with Gemini</Text> */}
            <Text style={styles.buttonText}>Generate Meal Plan </Text>
          </View>
        )}
      </TouchableOpacity>

      {mealPlan && (
        <View style={styles.mealPlanContainer}>
          <Text style={styles.mealPlanTitle}>Your AI-Generated Meal Plan</Text>
          {mealPlan.breakfast && <MealPlanDisplay title="Breakfast" meals={mealPlan.breakfast} />}
          {mealPlan.lunch && <MealPlanDisplay title="Lunch" meals={mealPlan.lunch} />}
          {mealPlan.snacks && <MealPlanDisplay title="Snacks" meals={mealPlan.snacks} />}
          {mealPlan.dinner && <MealPlanDisplay title="Dinner" meals={mealPlan.dinner} />}
        </View>
      )}
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    padding: 20,
    backgroundColor: '#fff',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    marginBottom: 20,
  },
  exampleContainer: {
    marginHorizontal: 20,
    marginBottom: 10,
  },
  exampleTitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  exampleText: {
    fontSize: 14,
    color: '#888',
    marginBottom: 2,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#f5f5f5',
    margin: 20,
    borderRadius: 12,
    padding: 15,
  },
  inputIcon: {
    marginRight: 10,
    marginTop: 5,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    textAlignVertical: 'top',
  },
  generateButton: {
    backgroundColor: '#FF6B00',
    margin: 20,
    borderRadius: 12,
    padding: 16,
  },
  generateButtonDisabled: {
    backgroundColor: '#ffab7a',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingIcon: {
    marginRight: 8,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  mealPlanContainer: {
    padding: 20,
  },
  mealPlanTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
  },
});

export default Diet;